<?php
/**
 * PropertyIdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HAPI Command API
 *
 * API for creating/updating/canceling objects in PMS
 *
 * OpenAPI spec version: v1-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PropertyIdTest Class Doc Comment
 *
 * @category    Class
 * @description Property id in HAPI system
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PropertyIdTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PropertyId"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "chain_code"
     */
    public function testPropertyChainCode()
    {
    }

    /**
     * Test attribute "brand_code"
     */
    public function testPropertyBrandCode()
    {
    }

    /**
     * Test attribute "property_code"
     */
    public function testPropertyPropertyCode()
    {
    }
}
