<?php
/**
 * ReservationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  HapiCommand
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
* HAPI Command API
 *
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
* OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.4
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace HapiCommand;

use HapiCommand\Configuration;
use HapiCommand\ApiException;
use HapiCommand\ObjectSerializer;

/**
 * ReservationApiTest Class Doc Comment
 *
 * @category Class
 * @package  HapiCommand
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReservationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelReservation
     *
     * Cancel reservation.
     *
     */
    public function testCancelReservation()
    {
    }

    /**
     * Test case for createReservation
     *
     * Create reservation.
     *
     */
    public function testCreateReservation()
    {
    }

    /**
     * Test case for updateReservation
     *
     * Update reservation.
     *
     */
    public function testUpdateReservation()
    {
    }
}
